x-variaveis: &variaveis
    RABBITMQ_DEFAULT_USER: "admin"
    RABBITMQ_DEFAULT_PASS: "sua_senha_super_segura"
    RABBITMQ_ERLANG_COOKIE: "server"

services:
  rabbitmq:
    image: rabbitmq:3.11-management
    environment:
      <<: *variaveis
    #ports:
    #  - 25672:25672
    #  - 15672:15672
    #  - 5672:5672
    #  - 4369:4369
    networks:
      - externa
      - interna
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.rabbitmq.entrypoints: "websecure"
        traefik.http.routers.rabbitmq.tls.certresolver: "le"
        traefik.http.services.rabbitmq.loadbalancer.server.port: 15672
        traefik.http.routers.rabbitmq.service: "rabbitmq"
        traefik.http.routers.rabbitmq.rule: "Host(`${SUBDOMAIN:-rabbitmq}.${DOMAIN:-seudominio.com.br}`)"

networks:
  externa:
    external: true
  interna:
    external: true