x-variaveis: &variaveis
    RABBITMQ_DEFAULT_USER: "${SEU_EMAIL}"
    RABBITMQ_DEFAULT_PASS: "${SUA_SENHA}"
    RABBITMQ_ERLANG_COOKIE: "server"

services:
  rabbitmq:
    image: rabbitmq:3.11-management
    hostname: rabbitmq
    environment:
      <<: *variaveis
    #ports:
    #  - 25672:25672
    #  - 15672:15672
    #  - 5672:5672
    #  - 4369:4369
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      # - rabbitmq_config:/etc/rabbitmq
    networks:
      - externa
      - interna
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.rabbitmq.entrypoints: "websecure"
        traefik.http.routers.rabbitmq.tls.certresolver: "le"
        traefik.http.services.rabbitmq.loadbalancer.server.port: 15672
        traefik.http.routers.rabbitmq.service: "rabbitmq"
        traefik.http.routers.rabbitmq.rule: "Host(`${SUBDOMAIN:-rabbitmq}.${DOMAIN:-seudominio.com.br}`)"
volumes:
  rabbitmq_data:
    external: true
    name: rabbitmq_data
  # rabbitmq_config:
networks:
  externa:
    external: true
  interna:
    external: true
