version: "3.7"
services:
  mysql:
    image: percona:8
    hostname: "{{.Service.Name}}.{{.Task.Slot}}"
    command:
      [
        --character-set-server=utf8mb4,
        --collation-server=utf8mb4_general_ci,
        --sql-mode=,
        --default-authentication-plugin=mysql_native_password,
        --max-allowed-packet=512MB,
        --port=3306,
      ]
    networks:
      - externa
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - TZ=America/Fortaleza
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          # - node.hostname == database
      resources:
        limits:
          cpus: "1"
          memory: 1024M

volumes:
  mysql_data:
    external: true
    name: mysql_data

networks:
  externa:
    external: true
    name: externa